In [3]:
a=10
b=10
print(a+b)

20


In [4]:
! pip install torch

In [5]:
import torch 
t1=torch.tensor([[1,2,3],[4,5,6]])
t1

tensor([[1, 2, 3],
        [4, 5, 6]])

In [6]:
t1=torch.tensor([[1,2],[4,5]])
#t2=([[1,2],[3,4]], device='cuda:0')
t3=torch.tensor([[1,2], [3,4]], dtype=torch.float64)
print(t1)
print(t3)



tensor([[1, 2],
        [4, 5]])
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [7]:
tf=torch.FloatTensor([[1,2],[3,4]])
tl=torch.LongTensor([[1,2],[3,4]])
tb=torch.ByteTensor([True,False,False,True])

print(tf)
print(tl)
print(tb)


tensor([[1., 2.],
        [3., 4.]])
tensor([[1, 2],
        [3, 4]])
tensor([1, 0, 0, 1], dtype=torch.uint8)


In [8]:
import numpy as np 
x = np.array([[1,2],[3,4]])
print(x, type(x))
print(x)
print(type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>
[[1 2]
 [3 4]]
<class 'numpy.ndarray'>


In [9]:
t=torch.from_numpy(x)
print(t)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [10]:
x1 = t.numpy()
print(x1, type(x1))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [11]:
print(tf.long())

tensor([[1, 2],
        [3, 4]])


In [12]:
print(tf.float())

tensor([[1., 2.],
        [3., 4.]])


In [13]:
print(tf.byte())

tensor([[1, 2],
        [3, 4]], dtype=torch.uint8)


텐서 크기 구하기

In [14]:
x=np.arange(1,13).reshape(3,2,2)
x

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [15]:
print('numpy  배열', x.shape)


numpy  배열 (3, 2, 2)


In [16]:
a = np.arange(1,5).reshape(2,2)
b = np.arange(2,10,2).reshape(2,2)
print(a)
print(b)
ta= torch.from_numpy(a)
tb= torch.from_numpy(b)
print(ta)
print(tb)

[[1 2]
 [3 4]]
[[2 4]
 [6 8]]
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
tensor([[2, 4],
        [6, 8]], dtype=torch.int32)


tensor의 연산

In [17]:
print(ta+tb)
print(ta-tb)
print(ta*tb)
print(ta/tb)
print(ta//tb)
print(ta==tb)
print(ta!=tb)

tensor([[ 3,  6],
        [ 9, 12]], dtype=torch.int32)
tensor([[-1, -2],
        [-3, -4]], dtype=torch.int32)
tensor([[ 2,  8],
        [18, 32]], dtype=torch.int32)
tensor([[0.5000, 0.5000],
        [0.5000, 0.5000]])
tensor([[0, 0],
        [0, 0]], dtype=torch.int32)
tensor([[False, False],
        [False, False]])
tensor([[True, True],
        [True, True]])


In [18]:
print(ta)
print(ta.mul_(tb))
print(ta)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
tensor([[ 2,  8],
        [18, 32]], dtype=torch.int32)
tensor([[ 2,  8],
        [18, 32]], dtype=torch.int32)


In [19]:
x=np.arange(1,5).reshape(2,2)
t1=torch.from_numpy(x)
y=1
print(t1)
print(t1+y)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
tensor([[2, 3],
        [4, 5]], dtype=torch.int32)


In [20]:
t2=torch.tensor([1,2])
print(t1)
print(t2)
print(t1+t2)


tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
tensor([1, 2])
tensor([[2, 4],
        [4, 6]])


In [21]:
t3=np.arange(1,7).reshape(2,3)
print(t1+t3)

ValueError: operands could not be broadcast together with shapes (2,2) (2,3) 

In [36]:
x=np.arange(1,13).reshape(3,2,2)
X=torch.from_numpy(x)
x

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [42]:
x = torch.FloatTensor(8,4)

chunks = x.chunk(3,dim=0)

for c in chunks:
    print(c.size())

torch.Size([3, 4])
torch.Size([3, 4])
torch.Size([2, 4])


In [49]:
x=np.arange(1,19).reshape(2,3,3)
x=torch.from_numpy(x)
print(x)
indice=torch.LongTensor([2,1])
y=x.index_select(dim=1, index=indice)
print(y)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]], dtype=torch.int32)
tensor([[[ 7,  8,  9],
         [ 4,  5,  6]],

        [[16, 17, 18],
         [13, 14, 15]]], dtype=torch.int32)


In [52]:
x=torch.randperm(3**3).reshape(3,3,-1)
print(x)

tensor([[[23, 12,  2],
         [18, 16,  7],
         [ 1, 13,  0]],

        [[ 5, 20, 14],
         [10, 15,  9],
         [25, 11,  6]],

        [[22,  4, 19],
         [ 8,  3, 24],
         [17, 21, 26]]])


In [53]:
y1=x.argmax(dim=-1)
print(y1)

tensor([[0, 0, 1],
        [1, 1, 0],
        [0, 2, 2]])


In [23]:
x=torch.FloatTensor([i for i in range(3**2)]).reshape(3,-1)
print(x)
print(x.shape)

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])
torch.Size([3, 3])


In [24]:
mask=x>4
print(mask)

tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])


In [25]:
y=x.masked_fill(mask,value=-1)
print(y)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4., -1.],
        [-1., -1., -1.]])


In [26]:
a=torch.ones(2,3)
b=torch.zeros(2,3)

print(a)
print(b)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [28]:
y=x.view(3,3)
print(y)

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])


In [29]:
y1=torch.ones_like(y)
y2=torch.zeros_like(y)
print(y1)
print(y2)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
