In [1]:
import torch
import torch.nn.functional as F

In [3]:
z=torch.FloatTensor([1,2,3])
y_hat=F.softmax(z, dim=0) #1차원 배열
print(y_hat)
print(y_hat.sum()) #확률의 합은 1

tensor([0.0900, 0.2447, 0.6652])
tensor(1.)


In [7]:
z=torch.rand(3,5, requires_grad=True) #3,5의 2차원 배열
print(z)
y_hat=F.softmax(z, dim=1) #1차원 배열
print(y_hat)
print(y_hat.sum(dim=1)) #확률의 합은 1

tensor([[0.3306, 0.0485, 0.5048, 0.6521, 0.7716],
        [0.2626, 0.8380, 0.4363, 0.7433, 0.6211],
        [0.9159, 0.0565, 0.3596, 0.1083, 0.8388]], requires_grad=True)
tensor([[0.1701, 0.1283, 0.2025, 0.2346, 0.2644],
        [0.1425, 0.2534, 0.1696, 0.2305, 0.2040],
        [0.2969, 0.1257, 0.1702, 0.1324, 0.2748]], grad_fn=<SoftmaxBackward0>)
tensor([1., 1., 1.], grad_fn=<SumBackward1>)


In [18]:
y=torch.randint(5,(3,)).long() #3개의 정수 랜덤값 (0~4)
print(y)
print(y_hat)
y_one_hot=torch.zeros_like(y_hat)
print(y_one_hot) # 처음은 0으로 초기화
print(y.unsqueeze(1)) #1차원 배열을 2차원 배열로 변환

tensor([3, 3, 0])
tensor([[0.1701, 0.1283, 0.2025, 0.2346, 0.2644],
        [0.1425, 0.2534, 0.1696, 0.2305, 0.2040],
        [0.2969, 0.1257, 0.1702, 0.1324, 0.2748]], grad_fn=<SoftmaxBackward0>)
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[3],
        [3],
        [0]])
