In [1]:
import torch
import torch.nn.functional as F

In [3]:
z=torch.FloatTensor([1,2,3])
y_hat=F.softmax(z, dim=0) #1차원 배열
print(y_hat)
print(y_hat.sum()) #확률의 합은 1

tensor([0.0900, 0.2447, 0.6652])
tensor(1.)


In [7]:
z=torch.rand(3,5, requires_grad=True) #3,5의 2차원 배열
print(z)
y_hat=F.softmax(z, dim=1) #1차원 배열
print(y_hat)
print(y_hat.sum(dim=1)) #확률의 합은 1

tensor([[0.3306, 0.0485, 0.5048, 0.6521, 0.7716],
        [0.2626, 0.8380, 0.4363, 0.7433, 0.6211],
        [0.9159, 0.0565, 0.3596, 0.1083, 0.8388]], requires_grad=True)
tensor([[0.1701, 0.1283, 0.2025, 0.2346, 0.2644],
        [0.1425, 0.2534, 0.1696, 0.2305, 0.2040],
        [0.2969, 0.1257, 0.1702, 0.1324, 0.2748]], grad_fn=<SoftmaxBackward0>)
tensor([1., 1., 1.], grad_fn=<SumBackward1>)


In [21]:
y=torch.randint(5,(3,)).long() #3개의 정수 랜덤값 (0~4)
print(y)
print(y_hat)
y_one_hot=torch.zeros_like(y_hat)
print(y_one_hot) # 처음은 0으로 초기화
print(y.unsqueeze(1)) #1차원 배열을 2차원 배열로 변환

y_one_hot.scatter_(1,y.unsqueeze(1),2) #y_one_hot에 y.unsqueeze(1)의 값을 2로 채움
print(y_one_hot)

tensor([0, 3, 3])
tensor([[0.1701, 0.1283, 0.2025, 0.2346, 0.2644],
        [0.1425, 0.2534, 0.1696, 0.2305, 0.2040],
        [0.2969, 0.1257, 0.1702, 0.1324, 0.2748]], grad_fn=<SoftmaxBackward0>)
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[0],
        [3],
        [3]])
tensor([[2., 0., 0., 0., 0.],
        [0., 0., 0., 2., 0.],
        [0., 0., 0., 2., 0.]])


In [22]:
import torch.nn as nn 
import torch.optim as optim

In [23]:
torch.manual_seed(1)
x_data=[[1,2,1,1],
        [2,1,3,2],
        [3,1,3,4],
        [4,1,5,5],
        [1,7,5,5],
        [1,2,5,6],
        [1,6,6,6],
        [1,7,7,7]]
y_data=[2,2,2,1,1,1,0,0]

In [24]:
x_train=torch.FloatTensor(x_data)
y_train=torch.LongTensor(y_data) # 정수값 - 반드시 LongTensor로 변환
print(x_train.size())
print(y_train.size())

torch.Size([8, 4])
torch.Size([8])


In [26]:
y_one_hot=torch.zeros(8,3) # 8개의 데이터, 3개의 클래스
print(y_one_hot)

#one-hot encoding
y_one_hot.scatter_(1,y_train.unsqueeze(1),1) #y_train.unsqueeze(1)의 값을 1로 채움
print(y_one_hot) 

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [1., 0., 0.],
        [1., 0., 0.]])


In [27]:
w=torch.zeros((4,3), requires_grad=True)
b=torch.zeros((1,3), requires_grad=True) #bias 1행 3열
print(w)
print(b)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], requires_grad=True)
tensor([[0., 0., 0.]], requires_grad=True)


In [28]:
optimizer = optim.SGD([w,b], lr=0.1)
epochs=10001

In [31]:
for epoch in range(epochs): 
    y_hat=F.softmax(x_train.matmul(w)+b, dim=1) #softmax
    cost=(y_one_hot* -torch.log(y_hat)).sum(dim=1).mean() #cross entropy

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch%100 ==0:
        print(epoch, cost.item())
        

0 1.0986123085021973
100 0.7041995525360107
200 0.6229996085166931
300 0.5657169222831726
400 0.5152913331985474
500 0.46766167879104614
600 0.4212779700756073
700 0.3754016160964966
800 0.3297654986381531
900 0.2850721478462219
1000 0.2481546849012375
1100 0.23267611861228943
1200 0.22139869630336761
1300 0.21112915873527527
1400 0.20173649489879608
1500 0.1931133270263672
1600 0.18516966700553894
1700 0.1778293251991272
1800 0.17102724313735962
1900 0.16470739245414734
2000 0.15882128477096558
2100 0.15332657098770142
2200 0.14818626642227173
2300 0.14336799085140228
2400 0.1388428956270218
2500 0.13458555936813354
2600 0.13057351112365723
2700 0.12678645551204681
2800 0.12320639193058014
2900 0.1198171004652977
3000 0.11660401523113251
3100 0.11355391144752502
3200 0.11065512150526047
3300 0.10789669305086136
3400 0.10526886582374573
3500 0.10276280343532562
3600 0.10037018358707428
3700 0.09808389842510223
3800 0.09589694440364838
3900 0.0938030406832695
4000 0.09179650247097015
41

In [34]:
y_hat=F.softmax(x_train.matmul(w)+b, dim=1)
print(y_hat) 
print(y_one_hot) 

tensor([[7.9508e-11, 6.5690e-06, 9.9999e-01],
        [1.7811e-04, 1.9474e-02, 9.8035e-01],
        [1.1670e-13, 4.1809e-02, 9.5819e-01],
        [6.1379e-10, 9.6248e-01, 3.7520e-02],
        [7.2622e-02, 9.2453e-01, 2.8516e-03],
        [3.8537e-02, 9.6146e-01, 7.0804e-08],
        [9.1230e-01, 8.7705e-02, 8.1008e-08],
        [9.9212e-01, 7.8797e-03, 5.7659e-11]], grad_fn=<SoftmaxBackward0>)
tensor([[0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [1., 0., 0.],
        [1., 0., 0.]])


In [39]:
for y in y_hat:
    #print(torch.argmax(y)) #가장 큰 값의 인덱스 출력
    print(y.argmax().item()) #가장 큰 값의 인덱스 출력

2
2
2
1
1
1
0
0


In [46]:
import sklearn.datasets as datasets
iris=datasets.load_iris()
iris.target #0,1,2 


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [47]:
x_train=torch.FloatTensor(iris.data)
y_train=torch.LongTensor(iris.target) 

print(x_train.size())
print(y_train.size())

torch.Size([150, 4])
torch.Size([150])


In [49]:
model = nn.Linear(4,3) 
 #4개의 특성, 3개의 클래스 (input=4, output=3)
optimizer=optim.SGD(model.parameters(), lr=0.1)
epochs=10001


In [50]:
for epoch in range(epochs):
    y_hat=model(x_train)
    cost=F.cross_entropy(y_hat, y_train) #cross entropy

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch%100 ==0:
        print(epoch, cost.item())
        

0 1.7532501220703125
100 0.4651300609111786
200 0.2666434347629547
300 0.22042623162269592
400 0.19214804470539093
500 0.1727110594511032
600 0.15846771001815796
700 0.1475398689508438
800 0.1388620287179947
900 0.13178418576717377
1000 0.12588708102703094
1100 0.12088768184185028
1200 0.11658785492181778
1300 0.1128445565700531
1400 0.1095518246293068
1500 0.10662936419248581
1600 0.10401521623134613
1700 0.10166074335575104
1800 0.09952720999717712
1900 0.0975833311676979
2000 0.0958036258816719
2100 0.09416702389717102
2200 0.09265591949224472
2300 0.09125566482543945
2400 0.08995378017425537
2500 0.08873960375785828
2600 0.08760404586791992
2700 0.08653924614191055
2800 0.08553832024335861
2900 0.08459535241127014
3000 0.08370509743690491
3100 0.0828629657626152
3200 0.08206485956907272
3300 0.08130716532468796
3400 0.08058667927980423
3500 0.07990051805973053
3600 0.07924610376358032
3700 0.07862108200788498
3800 0.07802338153123856
3900 0.07745108753442764
4000 0.0769024863839149

In [55]:
predict=model(x_train)
#print(predict)

accuracys=[]

for i in range(len(predict)):
    accuracys.append(y_train[i]==predict.argmax(dim=1)[i].item())

print(len(accuracys), torch.FloatTensor(accuracys).sum()) # 
print(torch.FloatTensor(accuracys).sum()/len(accuracys)) #정확도 

150 tensor(147.)
tensor(0.9800)
