In [1]:
def my_fun1(x):
    return x **2

In [6]:
def my_fun2(x):
    return 2*x**2 + 3*x + 1

In [2]:
def numerical_derivate(f,x): 
    delta_x = 1e-4

    return (f(x+delta_x)-f(x-delta_x))/(2*delta_x) 

In [9]:
result2 = numerical_derivate(my_fun2, 2)
print(result2)

11.00000000000989


In [5]:
result=numerical_derivate(my_fun1,3)
print(result)

6.000000000012662


In [11]:
import numpy as np

def numerical_derivative2(f, x):
    delta_x = 1e-4
    grad = np.zeros_like(x)
    print('x:', x)
    print('grad:', grad)

    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])

    while not it.finished:
        idx = it.multi_index
        print('idx:', idx, 'x[idx]:', x[idx])
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x)
        x[idx] = float(tmp_val) - delta_x
        fx2 = f(x)
        grad[idx] = (fx1 - fx2) / (2 * delta_x)
        print('grad[idx]:', grad[idx])
        print('grad:', grad)

        x[idx] = tmp_val
        it.iternext()

    return grad

In [12]:
def func3(input):
    x = input[0]
    y = input[1]

    return (2*x + 3*x*y + np.power(y,3))

In [13]:
numerical_derivative2(func3, np.array([1.0, 2.0]))

x: [1. 2.]
grad: [0. 0.]
idx: (0,) x[idx]: 1.0
grad[idx]: 7.999999999990237
grad: [8. 0.]
idx: (1,) x[idx]: 2.0
grad[idx]: 15.000000010019221
grad: [ 8.         15.00000001]


array([ 8.        , 15.00000001])

In [14]:
numerical_derivative2(func3, np.array([2.0, 3.0]))

x: [2. 3.]
grad: [0. 0.]
idx: (0,) x[idx]: 2.0
grad[idx]: 11.00000000000989
grad: [11.  0.]
idx: (1,) x[idx]: 3.0
grad[idx]: 33.000000010048325
grad: [11.         33.00000001]


array([11.        , 33.00000001])

In [15]:
numerical_derivative2(my_fun1, np.array([1.0]))

x: [1.]
grad: [0.]
idx: (0,) x[idx]: 1.0
grad[idx]: 1.9999999999992246
grad: [2.]


C:\Users\it\AppData\Local\Temp\ipykernel_13444\1789938787.py:19: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  grad[idx] = (fx1 - fx2) / (2 * delta_x)


array([2.])

2차원 배열로

In [16]:
arr1=np.array([[1.0, 2.0], [3.0, 4.0]])
arr1

array([[1., 2.],
       [3., 4.]])

In [18]:
def func4(input):
    w = input[0][0]
    x = input[0][1]
    y = input[1][0]
    z = input[1][1]

    return (w*x + x*y*z + 3*w + z*np.power(y,2))
    

In [19]:
numerical_derivative2(func4, arr1)

x: [[1. 2.]
 [3. 4.]]
grad: [[0. 0.]
 [0. 0.]]
idx: (0, 0) x[idx]: 1.0
grad[idx]: 5.000000000023874
grad: [[5. 0.]
 [0. 0.]]
idx: (0, 1) x[idx]: 2.0
grad[idx]: 13.00000000000523
grad: [[ 5. 13.]
 [ 0.  0.]]
idx: (1, 0) x[idx]: 3.0
grad[idx]: 32.00000000006753
grad: [[ 5. 13.]
 [32.  0.]]
idx: (1, 1) x[idx]: 4.0
grad[idx]: 15.000000000000568
grad: [[ 5. 13.]
 [32. 15.]]


array([[ 5., 13.],
       [32., 15.]])