In [14]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import numpy as np

In [15]:
torch.manual_seed(1)
x_data = torch.FloatTensor([[1, 2], [2, 3], [3, 4], [4, 5], [5, 6]])
t_data=torch.FloatTensor([[3],[5],[7],[9],[11]])

In [16]:
model=nn.Linear(2,1) # input_dim=1, output_dim=1, y=wx+b
print(list(model.parameters()))

[Parameter containing:
tensor([[ 0.3643, -0.3121]], requires_grad=True), Parameter containing:
tensor([-0.1371], requires_grad=True)]


In [17]:
optimizer=optim.SGD(model.parameters(), lr=0.01)
epochs=20001

In [18]:
for epoch in range(epochs):
    h=model(x_data)
    cost=F.mse_loss(h, t_data)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch%100==0:
        print('epoch:', epoch, 'cost:', cost.item(), model.parameters())

epoch: 0 cost: 60.767311096191406 <generator object Module.parameters at 0x000001F6D745F920>
epoch: 100 cost: 0.0007436164887621999 <generator object Module.parameters at 0x000001F6D15B3D80>
epoch: 200 cost: 0.0003317811351735145 <generator object Module.parameters at 0x000001F6D15B3D80>
epoch: 300 cost: 0.00014803984959144145 <generator object Module.parameters at 0x000001F6D15B3D80>
epoch: 400 cost: 6.605165253859013e-05 <generator object Module.parameters at 0x000001F6D15B3D80>
epoch: 500 cost: 2.9471522793755867e-05 <generator object Module.parameters at 0x000001F6D15B3D80>
epoch: 600 cost: 1.3149877304385882e-05 <generator object Module.parameters at 0x000001F6D15B3D80>
epoch: 700 cost: 5.867083928023931e-06 <generator object Module.parameters at 0x000001F6D745F920>
epoch: 800 cost: 2.61705758930475e-06 <generator object Module.parameters at 0x000001F6D15B3CA0>
epoch: 900 cost: 1.1679952649501502e-06 <generator object Module.parameters at 0x000001F6D15B3CA0>
epoch: 1000 cost: 5.21

In [21]:
# 새로운 데이터에 대한 예측
new_data = torch.FloatTensor([[7, 8], [8, 9], [9, 10]])
predictions = model(new_data)
print(predictions)
print(list(model.parameters()))


tensor([[15.0000],
        [17.0000],
        [19.0000]], grad_fn=<AddmmBackward0>)
[Parameter containing:
tensor([[1.1798, 0.8202]], requires_grad=True), Parameter containing:
tensor([0.1798], requires_grad=True)]
