In [25]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim


In [26]:
torch.manual_seed(1)

x_train=torch.FloatTensor([[1],[2],[3],[4],[5]]) #2차원 텐서로 선언
y_train=torch.FloatTensor([[2],[4],[6],[8],[10]])

print(x_train)
print(y_train)
print(x_train.size())
print(y_train.size())


tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.]])
tensor([[ 2.],
        [ 4.],
        [ 6.],
        [ 8.],
        [10.]])
torch.Size([5, 1])
torch.Size([5, 1])


In [27]:
W=torch.zeros(1, requires_grad=True)
print(W)
b=torch.zeros(1, requires_grad=True)
print(b)

tensor([0.], requires_grad=True)
tensor([0.], requires_grad=True)


In [28]:
h=x_train*W+b
print(h)

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [29]:
cost = torch.mean((h-y_train)**2)
print(cost)

tensor(44., grad_fn=<MeanBackward0>)


In [30]:
optimizer=optim.SGD([W,b], lr=0.01)

In [31]:
optimizer.zero_grad()

In [32]:
cost.backward()

In [33]:
optimizer.step()

In [34]:
epochs=2000
for epoch in range(epochs):
    h=x_train*W+b

    cost=torch.mean((h-y_train)**2)
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, epochs, W.item(), b.item(), cost.item()
        ))

Epoch    0/2000 W: 0.776, b: 0.211 Cost: 25.660801
Epoch  100/2000 W: 1.899, b: 0.364 Cost: 0.024309
Epoch  200/2000 W: 1.928, b: 0.260 Cost: 0.012348
Epoch  300/2000 W: 1.949, b: 0.185 Cost: 0.006272
Epoch  400/2000 W: 1.963, b: 0.132 Cost: 0.003186
Epoch  500/2000 W: 1.974, b: 0.094 Cost: 0.001619
Epoch  600/2000 W: 1.981, b: 0.067 Cost: 0.000822
Epoch  700/2000 W: 1.987, b: 0.048 Cost: 0.000418
Epoch  800/2000 W: 1.991, b: 0.034 Cost: 0.000212
Epoch  900/2000 W: 1.993, b: 0.024 Cost: 0.000108
Epoch 1000/2000 W: 1.995, b: 0.017 Cost: 0.000055
Epoch 1100/2000 W: 1.997, b: 0.012 Cost: 0.000028
Epoch 1200/2000 W: 1.998, b: 0.009 Cost: 0.000014
Epoch 1300/2000 W: 1.998, b: 0.006 Cost: 0.000007
Epoch 1400/2000 W: 1.999, b: 0.004 Cost: 0.000004
Epoch 1500/2000 W: 1.999, b: 0.003 Cost: 0.000002
Epoch 1600/2000 W: 1.999, b: 0.002 Cost: 0.000001
Epoch 1700/2000 W: 2.000, b: 0.002 Cost: 0.000000
Epoch 1800/2000 W: 2.000, b: 0.001 Cost: 0.000000
Epoch 1900/2000 W: 2.000, b: 0.001 Cost: 0.000000

In [35]:
h=torch.FloatTensor([7])*W+b
print(h)

tensor([13.9994], grad_fn=<AddBackward0>)


In [36]:
import torch
w=torch.tensor(2.0, requires_grad=True)
print(w)

tensor(2., requires_grad=True)


In [37]:
nb_epochs = 20
for epoch in range(nb_epochs +1):
    z=2*W
    z.backward()
    print('수식을 w로 미분한 값: {}'.format(W.grad))

수식을 w로 미분한 값: tensor([1.9999])
수식을 w로 미분한 값: tensor([3.9999])
수식을 w로 미분한 값: tensor([5.9999])
수식을 w로 미분한 값: tensor([7.9999])
수식을 w로 미분한 값: tensor([9.9999])
수식을 w로 미분한 값: tensor([11.9999])
수식을 w로 미분한 값: tensor([13.9999])
수식을 w로 미분한 값: tensor([15.9999])
수식을 w로 미분한 값: tensor([17.9999])
수식을 w로 미분한 값: tensor([19.9999])
수식을 w로 미분한 값: tensor([21.9999])
수식을 w로 미분한 값: tensor([23.9999])
수식을 w로 미분한 값: tensor([25.9999])
수식을 w로 미분한 값: tensor([27.9999])
수식을 w로 미분한 값: tensor([29.9999])
수식을 w로 미분한 값: tensor([31.9999])
수식을 w로 미분한 값: tensor([33.9999])
수식을 w로 미분한 값: tensor([35.9999])
수식을 w로 미분한 값: tensor([37.9999])
수식을 w로 미분한 값: tensor([39.9999])
수식을 w로 미분한 값: tensor([41.9999])


In [38]:
torch.manual_seed(3)
print('랜덤 시드 3')
for i in range(1,3):
    print(torch.rand(1))

랜덤 시드 3
tensor([0.0043])
tensor([0.1056])


In [39]:
torch.manual_seed(5)
print('랜덤 시드 5')
for i in range(1,3):
    print(torch.rand(1))

랜덤 시드 5
tensor([0.8303])
tensor([0.1261])


In [40]:
torch.manual_seed(3)
print('랜덤 시드 다시 3')
for i in range(1,3):
    print(torch.rand(1))

랜덤 시드 다시 3
tensor([0.0043])
tensor([0.1056])


In [41]:
import numpy as np 
x_data1=np.array([[1,2],[2,3],[3,4],[4,5],[5,6]]).reshape(5,2)
t_data1=np.array([3,5,7,9,11]).reshape(5,1)
print(x_data1)
print(t_data1)

[[1 2]
 [2 3]
 [3 4]
 [4 5]
 [5 6]]
[[ 3]
 [ 5]
 [ 7]
 [ 9]
 [11]]


In [42]:
x_data1=torch.from_numpy(x_data1).float()
t_data1=torch.from_numpy(t_data1).float()
print(x_data1)
print(t_data1)

tensor([[1., 2.],
        [2., 3.],
        [3., 4.],
        [4., 5.],
        [5., 6.]])
tensor([[ 3.],
        [ 5.],
        [ 7.],
        [ 9.],
        [11.]])


In [43]:
W=torch.zeros((2,1), requires_grad=True)
b=torch.zeros(1, requires_grad=True)


In [44]:
optimizer=optim.SGD([W,b], lr=1e-6)
epochs=200001
for epoch in range(epochs): 
    y=x_data1.matmul(W)+b
    cost=torch.mean((t_data1-y)**2)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print('epoch:' , epoch, cost.item(), 'W:', W, 'b:', b)

epoch: 0 57.0 W: tensor([[5.0000e-05],
        [6.4000e-05]], requires_grad=True) b: tensor([1.4000e-05], requires_grad=True)
epoch: 100 56.32481002807617 W: tensor([[0.0050],
        [0.0064]], requires_grad=True) b: tensor([0.0014], requires_grad=True)
epoch: 200 55.657630920410156 W: tensor([[0.0100],
        [0.0128]], requires_grad=True) b: tensor([0.0028], requires_grad=True)
epoch: 300 54.99834060668945 W: tensor([[0.0149],
        [0.0191]], requires_grad=True) b: tensor([0.0042], requires_grad=True)
epoch: 400 54.34687423706055 W: tensor([[0.0198],
        [0.0254]], requires_grad=True) b: tensor([0.0055], requires_grad=True)
epoch: 500 53.70311737060547 W: tensor([[0.0247],
        [0.0316]], requires_grad=True) b: tensor([0.0069], requires_grad=True)
epoch: 600 53.06699752807617 W: tensor([[0.0295],
        [0.0378]], requires_grad=True) b: tensor([0.0083], requires_grad=True)
epoch: 700 52.43841552734375 W: tensor([[0.0343],
        [0.0439]], requires_grad=True) b: tensor(

In [48]:
def predict(x):
    h=x.matmul(W)+b
    return h

In [49]:
predict(torch.FloatTensor([[10,11]]))

tensor([[20.4867]], grad_fn=<AddBackward0>)

In [11]:
import pandas as pd

# CSV 파일 읽기
df = pd.read_csv('../data/data-01-test-score.csv', header=None)

df

# 데이터 프레임의 첫 몇 행 출력


0   1    2    3
0   73  80   75  152
1   93  88   93  185
2   89  91   90  180
3   96  98  100  196
4   73  66   70  142
5   53  46   55  101
6   69  74   77  149
7   47  56   60  115
8   87  79   90  175
9   79  70   88  164
10  69  70   73  141
11  70  65   74  141
12  93  95   91  184
13  79  80   73  152
14  70  73   78  148
15  93  89   96  192
16  78  75   68  147
17  81  90   93  183
18  88  92   86  177
19  78  83   77  159
20  82  86   90  177
21  86  82   89  175
22  78  83   85  175
23  76  83   71  149
24  96  93   95  192

In [9]:
data=df.values
x_data1=data[:,:3].reshape(-1,3)
y_data1=data[:,-1].reshape(-1,1)
print(x_data1)
print(y_data1)

[[ 93  88  93]
 [ 89  91  90]
 [ 96  98 100]
 [ 73  66  70]
 [ 53  46  55]
 [ 69  74  77]
 [ 47  56  60]
 [ 87  79  90]
 [ 79  70  88]
 [ 69  70  73]
 [ 70  65  74]
 [ 93  95  91]
 [ 79  80  73]
 [ 70  73  78]
 [ 93  89  96]
 [ 78  75  68]
 [ 81  90  93]
 [ 88  92  86]
 [ 78  83  77]
 [ 82  86  90]
 [ 86  82  89]
 [ 78  83  85]
 [ 76  83  71]
 [ 96  93  95]]
[[185]
 [180]
 [196]
 [142]
 [101]
 [149]
 [115]
 [175]
 [164]
 [141]
 [141]
 [184]
 [152]
 [148]
 [192]
 [147]
 [183]
 [177]
 [159]
 [177]
 [175]
 [175]
 [149]
 [192]]


In [27]:
import torch
import torch.optim as optim
import numpy as np

# 예시 데이터
x_data1 = np.array([[1], [2], [3], [4], [5]])
y_data1 = np.array([[2], [4], [6], [8], [10]])

# numpy 배열을 torch 텐서로 변환
x_train = torch.from_numpy(x_data1).float()
y_train = torch.from_numpy(y_data1).float()

# 가중치와 바이어스 초기화 (float 타입으로 변환)
W = torch.randn(1, dtype=torch.float32, requires_grad=True)
b = torch.randn(1, dtype=torch.float32, requires_grad=True)

# 옵티마이저 정의
optimizer = optim.SGD([W, b], lr=1e-6)

# 학습 설정
epochs = 30001
cost_list = []

# 학습 루프
for epoch in range(epochs):
    # 예측
    y = x_train.matmul(W) + b
    
    # 손실 계산
    cost = torch.mean((y - y_train) ** 2)
    
    # 역전파
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 100 == 0:
        print('epoch:', epoch, 'cost:', cost.item(), 'W:', W, 'b:', b.item())
        cost_list.append(cost.item())
""" 
# 학습된 모델의 파라미터 출력
print(f'Final Weight: {W.item():.4f}, Final Bias: {b.item():.4f}') """

epoch: 0 cost: 32.14033508300781 W: tensor([0.0341], requires_grad=True) b: 0.984781801700592
epoch: 100 cost: 32.0447883605957 W: tensor([0.0370], requires_grad=True) b: 0.985765278339386
epoch: 200 cost: 31.949729919433594 W: tensor([0.0399], requires_grad=True) b: 0.9867432713508606
epoch: 300 cost: 31.855104446411133 W: tensor([0.0429], requires_grad=True) b: 0.987720787525177
epoch: 400 cost: 31.760902404785156 W: tensor([0.0458], requires_grad=True) b: 0.9886983036994934
epoch: 500 cost: 31.66718292236328 W: tensor([0.0487], requires_grad=True) b: 0.9896706938743591
epoch: 600 cost: 31.57388687133789 W: tensor([0.0516], requires_grad=True) b: 0.990642249584198
epoch: 700 cost: 31.48101043701172 W: tensor([0.0545], requires_grad=True) b: 0.9916138052940369
epoch: 800 cost: 31.388599395751953 W: tensor([0.0573], requires_grad=True) b: 0.992580771446228
epoch: 900 cost: 31.296615600585938 W: tensor([0.0602], requires_grad=True) b: 0.9935463666915894
epoch: 1000 cost: 31.205049514770

" \n# 학습된 모델의 파라미터 출력\nprint(f'Final Weight: {W.item():.4f}, Final Bias: {b.item():.4f}') "

In [29]:
def predict(x):
    return x.matmul(W) + b

# 새로운 데이터에 대한 예측
new_data = torch.FloatTensor([[65], [68], [70]])
predictions = predict(new_data)
print(predictions)

tensor([44.1562, 46.1384, 47.4598], grad_fn=<AddBackward0>)
